POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBpIEJybyIsImlkIjoiNjc5NjZhZWQ2YTU5OWEwNjU1NTFhNmY0IiwiaWF0IjoxNzM3OTExMTkyfQ.tN17bBg5RpWP3zKdEQRV2iFKFtjTgdZs9BZXzOI6bbk

{
    "title": "Orbital Velocity",
    "author": "Pi AlMaslouhi",
    "url": "https://www.example.com",
    "userId": "679629ef1239573b6c5beddb"
}